// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import MobileMenuController from "./mobile_menu_controller"
import FiltersController from "./filters_controller"

application.register("hello", HelloController)
application.register("mobile-menu", MobileMenuController)
application.register("filters", FiltersController)
